dist: trusty
sudo: false  # allows use of faster container-based builds

language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy"
  - "pypy3"

install:
  - pip install tox tox-travis  # leaving out of requirements.txt b/c only needed by travis

script:
  - tox
